# Generated by Django 4.1.1 on 2022-09-26 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='States',
            fields=[
                ('state_id', models.IntegerField()),
                ('state', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Authentications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=16)),
                ('isApproved', models.BooleanField(default=False)),
                ('isAdmin', models.BooleanField(default=False)),
                ('state', models.ForeignKey(db_column='state', on_delete=django.db.models.deletion.CASCADE, to='auths.states')),
            ],
        ),
    ]
