# Generated by Django 3.2.15 on 2022-09-27 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentications',
            name='state',
            field=models.ForeignKey(db_column='state', null=True, on_delete=django.db.models.deletion.CASCADE, to='auths.states'),
        ),
    ]
