# Generated by Django 3.2.15 on 2022-09-28 09:21

import auths.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_alter_authentications_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='states',
            name='data',
            field=models.FileField(null=True, upload_to=auths.models.filepath),
        ),
    ]
